replicaCount: 1

image:
  repository: JWNewcomb/multiagent-predictive-maintenance # manual entry
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Application Configuration
appConfig:
  databaseName: "agentic_predictive_maintenance"
  awsRegion: "us-east-1"
  # Default completion model from repo
  completionModel: "us.anthropic.claude-3-5-haiku-20241022-v1:0" 
  # Default embedding model from repo
  embeddingModel: "cohere.embed-english-v3"

#manual addition
ezua:  
  domainName: "${DOMAIN_NAME}"
  #Use next options in order to configure the application endpoint.
  #Example of a VirtualService is here:
  virtualService:
    endpoint: "ls-app.${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"

  authorizationPolicy:
    namespace: "istio-system"
    providerName: "oauth2-proxy"
    matchLabels:
      istio: "ingressgateway"

# Sensitive Data (Leave empty here and pass via --set or separate values file)
secrets:
  mongodbUri: ""
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
